"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: inspire
  IDL file: inspire_hand_touch.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import inspire_dds


@dataclass
@annotate.final
@annotate.autoid("sequential")
class inspire_hand_touch(
    idl.IdlStruct, 
    # typename="inspire.inspire_hand_touch"
    typename="inspire_hand_msgs::msg::dds_::InspireHandTouch_",
    ):
    fingerone_tip_touch: types.sequence[types.int16, 9]
    fingerone_top_touch: types.sequence[types.int16, 96]
    fingerone_palm_touch: types.sequence[types.int16, 80]
    fingertwo_tip_touch: types.sequence[types.int16, 9]
    fingertwo_top_touch: types.sequence[types.int16, 96]
    fingertwo_palm_touch: types.sequence[types.int16, 80]
    fingerthree_tip_touch: types.sequence[types.int16, 9]
    fingerthree_top_touch: types.sequence[types.int16, 96]
    fingerthree_palm_touch: types.sequence[types.int16, 80]
    fingerfour_tip_touch: types.sequence[types.int16, 9]
    fingerfour_top_touch: types.sequence[types.int16, 96]
    fingerfour_palm_touch: types.sequence[types.int16, 80]
    fingerfive_tip_touch: types.sequence[types.int16, 9]
    fingerfive_top_touch: types.sequence[types.int16, 96]
    fingerfive_middle_touch: types.sequence[types.int16, 9]
    fingerfive_palm_touch: types.sequence[types.int16, 96]
    palm_touch: types.sequence[types.int16, 112]


